### ISSUE TITLE
Slider is not rendered: TypeError: Cannot read properties of undefined (reading 'state')

### ISSUE THREAD

**Issue by jsamr** [Nerwyn/android-tv-card#106]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 3.8.1

**Last working release (if known):** Not sure. I have tried 3.8.0 and 3.7.4 and could reproduce. Have cleared cache between each install.

**Browser and Operating System:**

- Arc Browser, 1.49.1
- MacOS 14.5 (23F79)

Could also reproduce in the Android companion app

**Description of problem:**

The slider is not rendered.

**Javascript errors shown in the web inspector (if applicable):**

```
android-tv-card.min.js:187 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'state')
    at c.setSliderState (android-tv-card.min.js:187:5287)
    at c.buildSlider (android-tv-card.min.js:195:51)
    at c.render (android-tv-card.min.js:217:38)
    at c.update (android-tv-card.min.js:390:101089)
    at c.performUpdate (android-tv-card.min.js:390:89065)
    at c.scheduleUpdate (android-tv-card.min.js:390:88601)
    at c._$EP (android-tv-card.min.js:390:88509)
```

**Your Full Remote Config**
The minimal reproduction:

```yaml
type: custom:android-tv-card
remote_id: remote.tcl_tv
rows:
  - - slider
```
![image](https://github.com/user-attachments/assets/17dbd5da-94f6-4f2e-ab08-dc895e95b77f)
![image](https://github.com/user-attachments/assets/d4508cbf-8bfc-4ae2-bf01-2494659b3929)

Note that other buttons work perfectly fine, I just omitted these for the purpose of minimally reproducing the issue.

**Additional information:**

DOM snapshot:

![image](https://github.com/user-attachments/assets/e2061f97-fe38-411a-95f3-98531f5f62d8)

**Comment by Nerwyn** [comment]
Read the README. You didn't provide a `slider_id` or `media_player_id`.

**Comment by jsamr** [comment]
@Nerwyn Oh crap, thank you!
