### ISSUE TITLE
Search on Kodi broke?

### ISSUE THREAD

**Issue by houser42** [Nerwyn/android-tv-card#112]
Hello,

One thing stopped working with the latest 3.9.1 release: The Kodi Search button.
The Text input button still works.
Downgrading does not fix it so I am wondering if something else has changed? 
Dependencies perhaps?
Have a look when you have a moment? Many thanks.

Here is the error;
```
Falled to call service remote send command, must contain at east one of entity id, device 1a, area 1a. 
toor 1d label lo
```
Here is my yaml:
```
type: custom:android-tv-card
keyboard_id: media_player.kodi
keyboard_mode: KODI
rows:
  - search
custom_keys:
  search:
    icon: mdi:search-web
    icon_height: 18px
    key: SEARCH
button_style:
  '--size': 24px
  '--padding': 0px
card_mod:
  style: |
    ha-card {
      padding: 0px !important;
    }
```

**Comment by Nerwyn** [comment]
Hey Houser. I think it's because the text is sending before the search dialog opens in Kodi. I thought I had fixed it during my testing and development but it looks like there wasn't enough time between opening the search page and sending the text. I've moved the open kodi search call to the showDialog function. Can you try the 3.9.2 alpha?

Also make sure to try the the `keyboard` action/button. It now supports Kodi and works better than it does on other platforms!

**Comment by houser42** [comment]
Hello @Nerwyn 
I am a little confused. For some reason when I update to 3.9.1 or later, I get the mentioned error. 
It then does not work to downgrade to any version for some reason.
I went back to my backup from a few days ago, that has 3.8.2 and works fine.
It seems to me that something in installing 3.9.1 or later breaks the search function.
No big deal here, as I am happy at 3.8.2 with my current install.
Would be happy to test any new versions when you get around to it? Many thanks!

**Comment by Nerwyn** [comment]
If downgrading doesn't work then it's definitely a caching issue, which is probably why 3.9.2 didn't work. It should be fixed now that it opens the Kodi search page when the dialog opens, so I'm going to close this issue. Please try 3.9.2 again after clearing cache on your devices.

**Comment by houser42** [comment]
Thanks for your suggestion. Clearing cashes does not help so far.
I will see if I have broken something else in terms of other addons or dependencies when I have time.
At the moment I am stumped and staying at 3.8.2.

**Comment by houser42** [comment]
Just checking: I only see 3.9.1 and 3.9.2 beta 001. Is that correct?  You mean try the beta?

**Comment by Nerwyn** [comment]
Yes. There were a few 3.9.2 alpha builds but once I was sure that I fixed this and a few other bugs I deleted them and made a beta build.

**Comment by houser42** [comment]
Ok, thanks!
Removing some code (specifically the custom key code) makes the search button work again. Could you just tell me how to add back an icon with this new version please?
The previous methodfor adding an icon  is not working and I noted that this is being changed at the moment from another similar issue report. Progress!

This is what works now:
```
type: custom:android-tv-card
entity_id: media_player.kodi
keyboard_id: media_player.kodi
keyboard_mode: KODI
rows:
  - search
button_style:
  '--size': 24px
  '--padding': 0px
  '--icon': mdi:search-web
card_mod:
  style: |
    ha-card {
      padding: 0px !important;
    }
```

This is what I used before:
```
type: custom:android-tv-card
keyboard_id: media_player.kodi
keyboard_mode: KODI
rows:
  - search
custom_keys:
  search:
    icon: mdi:search-web
    icon_height: 18px
    key: SEARCH
button_style:
  '--size': 24px
  '--padding': 0px
card_mod:
  style: |
    ha-card {
      padding: 0px !important;
    }
```

**Comment by Nerwyn** [comment]
Yeah that would break it. By setting key you're overwriting the default search action. This works for me

```yaml
  search:
    icon: mdi:kodi
    style:
      color: rgb(9, 179, 232)
      '--size': 64px
```

**Comment by houser42** [comment]
Ok. thanks! Where would that go into my last code[ just  above](https://github.com/Nerwyn/android-tv-card/issues/112#issuecomment-2256233955)

**Comment by Nerwyn** [comment]
It's a custom action, it replaces your old kodi search custom action.

```yaml
type: custom:android-tv-card
keyboard_id: media_player.kodi
keyboard_mode: KODI
rows:
  - search
custom_keys:
  search:
    icon: mdi:kodi
    style:
      color: rgb(9, 179, 232)
      '--size': 18px
button_style:
  '--size': 24px
  '--padding': 0px
card_mod:
  style: |
    ha-card {
      padding: 0px !important;
    }
```

**Comment by houser42** [comment]
You're a star. I got lost in breaking changes for a while. All good again. I appreciate you. Thanks for your help!
