### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by gralfj** [Nerwyn/android-tv-card#114]
sorry about the silly question, how do you do to indentate config files, cause I am investigating how to customize a tv card but in custom_actions dont know how to do it, or do I have to add a custom_actions row for every action?

**Comment by Nerwyn** [comment]
Using spaces? YAML (the config file format that Home Assistant uses) forces us to use spaces for indentation.

**Comment by gralfj** [comment]
sorry, solved, I was using a tablet, on the pc everything works as spected, false alarm.

by the way I like your project, I´ll be spending some time here.

thank you
