### ISSUE TITLE
 HACS 2.0 that was released lately broke the path for files in touchpad?

### ISSUE THREAD

**Issue by houser42** [Nerwyn/android-tv-card#120]
Hello,
Not really a bug, it just appears a change in HACS 2.0 that was released lately broke the path for files
in the touchpad. This is what has worked up to now here:
```
touchpad_style:
  height: 275px
  background-image: url("/hacsfiles/themes/jtm-bg/Kodi75b.png")
  background-size: xxx
  background-repeat: no-repeat
  background-position: center
  opacity: 0.4
  background-color: rgba(0, 0, 0, 0.2)
card_mod:
  style: |
    :host {
      --ha-card-background: #00000000;
```

💥 Breaking change in hacs:
The /hacsfiles/ endpoint no longer works for Themes.

full changelog: https://github.com/hacs/integration/compare/1.34.0...2.0.0

I tried simply replacing /hacsfiles/ with /config/  in the full path, but that seems to do nothing.

Grateful for any helpful suggestions when there is time. Many thanks.

**Comment by Nerwyn** [comment]
You shouldn't have been putting images in the hacsfiles folder in the first place. You're supposed to place images in the www folder and reference them using the URL local like `url('/local/kodi.png');`

![image](https://github.com/user-attachments/assets/74312f8a-88a1-4aae-8c21-314ada875b8f)
