### ISSUE TITLE
Seems like Roku DPAD remote buttons sent are incorrect

### ISSUE THREAD

**Issue by ponchohoncho** [Nerwyn/android-tv-card#121]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser

**Release with the issue:**
3.9.4

**Last working release (if known):**

**Description of problem:**

When I try to use the touchpad to control my Roku TV, I get messages about "Invalid response from Roku API". I believe it is because the card is sending the wrong command to the remote entity

**Javascript errors shown in the web inspector (if applicable):**

From HA Console:
```
2024-08-26 00:47:41.849 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140404460945216] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/roku/helpers.py", line 42, in wrapper
    await func(self, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/roku/remote.py", line 66, in async_send_command
    await self.coordinator.roku.remote(single_command)
  File "/usr/local/lib/python3.12/site-packages/rokuecp/rokuecp.py", line 369, in remote
    raise RokuError(msg)
rokuecp.exceptions.RokuError: Remote key is invalid: DPAD_CENTER
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/roku/helpers.py", line 51, in wrapper
    raise HomeAssistantError("Invalid response from Roku API") from error
homeassistant.exceptions.HomeAssistantError: Invalid response from Roku API
```

From the Chrome F12 Console:
```
{
    "code": "home_assistant_error",
    "message": "Invalid response from Roku API"
}
```

**Your Full Remote Config**

```yaml
type: custom:android-tv-card
platform: roku
remote_id: remote.upstairs_tv
slider_id: media_player.upstairs_tv
keyboard_id: remote.upstairs_tv
title: Example
custom_actions:
  slider:
    icon: mdi:music-note
rows:
  - - back
    - power
    - home
  - - keyboard
    - search
    - slider
  - - - netflix
      - null
      - youtube
      - null
      - spotify
    - touchpad
  - - previous
    - play_pause
    - next

```

**Additional information:**
The other buttons work. Power, back, home, all work properly with my TV. It's the DPAD buttons that don't.

I think that the important line from the console error is: `rokuecp.exceptions.RokuError: Remote key is invalid: DPAD_CENTER`

The Roku integration says that the valid remote buttons are "up", "down", etc without DPAD in the name: https://www.home-assistant.io/integrations/roku/

Could that be the issue?

I built a button-based dashboard to act as a remote, and this is what works for my roku buttons:
```
      - type: custom:mushroom-template-card
        tap_action:
          action: call-service
          service: remote.send_command
          service_data:
            command: right
          target:
            entity_id: remote.upstairs_tv
```

**Comment by Nerwyn** [comment]
You have to remap the direction buttons with custom actions. By default they send Android TV key commands. In version 4 I plan to add default key and source maps for multiple platforms so this won't be necessary.

**Comment by Nerwyn** [comment]
@ponchohoncho in [the v4 beta](https://github.com/Nerwyn/android-tv-card/releases/tag/4.0.0-beta.001) you can set the global plaform to Roku and it should use the default keys for Roku instead of Android TV.

**Comment by ponchohoncho** [comment]
Super cool! Thank you so much!

**Comment by Nerwyn** [comment]
Let me know if you run into any issues! I don't have a Roku or most of the other other platforms this card supports so I rely on user feedback to make sure what I wrote actually works.
