### ISSUE TITLE
Formula 1 TV Pro ?

### ISSUE THREAD

**Issue by ronaldpoelsma** [Nerwyn/android-tv-card#127]
Hi.
Love the new version!
Would love it even better if a button for F1TVPro (https://f1tv.formula1.com/) would become available. 
Any chance for that?

**Comment by Nerwyn** [comment]
You'll have to provide an icon and HA action for opening it. Assuming that your talking about Android TV (this project supports multiple platforms now!) it would be the deep link, which can be found using [this guide](https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921).

**Comment by Nerwyn** [comment]
Try the 4.1.0 alpha. I was told about the Firemote apps list in #144 and found the F1TV app ID there.

**Comment by ronaldpoelsma** [comment]
I tried by updating the universal-remote-card.min.js file. But how do I
update the icons?

**Comment by ronaldpoelsma** [comment]
Apologies for replying again.
I updated the card using the pre-release option. which worked OK I now have
the 4.10.0 version running.
However I still do not get the new icon(s), and thus cannot add a clickable
button to the card.
Any ideas?

**Comment by ronaldpoelsma** [comment]
Never mind. Following the redownload instructions made it available.....

**Comment by Nerwyn** [comment]
Is it working?

**Comment by ronaldpoelsma** [comment]
Almost.
When pressed it jumps to the playstore page for the app. See attached
photo.





Op wo 9 okt 2024 om 17:02 schreef Nerwyn ***@***.***>

**Comment by Nerwyn** [comment]
You can't attach photos when responding over email, you have to attach them through the actual issue thread.

Unfortunately that's an issue with Android TV. It also affects Max which has an open issue #77. Opening to the app store page is the best we can do for some apps.

**Comment by Nerwyn** [comment]
[Released 4.1.0.](https://github.com/Nerwyn/android-tv-card/releases/tag/4.1.0)
