### ISSUE TITLE
button change based on a state of an entity

### ISSUE THREAD

**Issue by ntk9** [Nerwyn/android-tv-card#133]
it will be great to have an option to change the button or the icon based on status of an entity

for exampale if the tv is mute the icon will be unmute and vise versa (play-pause...) 

or even change the all buton, for exampale if the tv  in home screen it will see buttons X X X if in netflix display buttuns Y Y Y if HDMI input is 2 display buttons Z Z Z

**Comment by Nerwyn** [comment]
You can already do all of this via templating. See [this example in the README](https://github.com/Nerwyn/android-tv-card?tab=readme-ov-file#example-13) for layouts based on entity states. You can change icons (or most anything else) of a custom action using similar templates.

**Comment by ntk9** [comment]
sorry i missed that, this is awesome! thanks
