### ISSUE TITLE
Slider reverse in RTL language 

### ISSUE THREAD

**Issue by ntk9** [Nerwyn/android-tv-card#134]
When using slider the volume is in reverse. Sliding up will decrease volume and sliding down will increase volume . The problem is only with RTL ( right to left ) languages. Try to use transform. And few other css changes. But with no success.

Video show the problem
https://youtu.be/Qg9icY4G-vk?si=HKAQyqcuIml-_Bk_

**Comment by Nerwyn** [comment]
I should add some kind of check for CSS `direction` modify sliders if it's `rtl`.

Should rtl horizontal sliders also be reversed? From what I see they are rtl, but while tooltip transforms and thumb styles are ltr.

**Comment by Nerwyn** [comment]
Can you try the 4.0.5 alpha? I think I've fixed both horizontal and vertical sliders.

**Comment by ntk9** [comment]
horizontal slider dont need to be reversed

the 4.0.5 alpha is working great and the slider in veritical is fixed! thanks you!

**Comment by Nerwyn** [comment]
The language direction rtl CSS setting also reverse the horizontal slider, it's thumb styles just weren't affected by it. If everything looks good I can officially release these fixes as a patch build.

**Comment by Nerwyn** [comment]
An alternate easier fix for all of this is to just set `direction: ltr` to either the `remote-slider` base styles or the entire card. This would also fix things like direction pads being incorrect and the remote layout being reversed with languages.

**Comment by Nerwyn** [comment]
Alright I've added some additional fixes for navigation buttons, dpad, xpad, and npad if you could do a final check @ntk9.

**Comment by ntk9** [comment]
Everything is working great in 009

The layout is not a problem. Because when you edit. you see it in reversed. Its like this in all home assistant cards and layouts. I personally edit the layout on pc in English but use the app in rtl. So i do on the pc everything in reverend. But most people use and edit in the same language. And even if they like me. They already used to do every layout in reversed. This remote is very powerful. Just started to make some lite slider with it. Amazing job. 🙏🙏🙏

**Comment by Nerwyn** [comment]
Released [4.0.5](https://github.com/Nerwyn/android-tv-card/releases/tag/4.0.5). And created some bugs for my other projects which also have RTL layout display issues 😅 .
