### ISSUE TITLE
v2.0.0-dev.006 creates a loop of commands at least on iPhone.

### ISSUE THREAD

**Issue by houser42** [Nerwyn/android-tv-card#14]
Updated to the latest version today.  v2.0.0-dev.006

It creates a loop at least on iPhone when using any swiping  command anywhere on all devices I use.
**Release with the issue is  v2.0.0-dev.006

**Last working release : 1.5.3

I only use the Iphone app for swiping so can not say anything about other platforms.
It just goes into a loop of vibrating and repeating commands.
Downgrading to 1.5.3 fixes the issue.

**Comment by Nerwyn** [comment]
I wouldn't use the dev builds unless you're willing to experience some super broken behavior. I rapid fire deploy those as part of my development and test workflow since it's the easiest way to get code from my desktop to my Home Assistant instance. It's been fixed in v2.0.0 proper.

**Comment by houser42** [comment]
Thanks for the comment. I am just now and then hoping and looking for those last swipe gestures  as this git has made it possible to get going with my HT remotes on HA ;)
I don't mind super broken behaviour, as I am still just learning and trying this out.
So you never want feedback one your dev builds?

**Comment by Nerwyn** [comment]
Yeah probably not. If something is broken in the dev builds it's likely because I tried something new and it failed, and it'll likely get fixed or reverted a few dev builds later.
