### ISSUE TITLE
WearOs Tile Card

### ISSUE THREAD

**Issue by giof94is** [Nerwyn/android-tv-card#140]
It would be great, if possible, to add the possibility to configure a WearOS tile card with some command to control a TV. Samsung SmartThings for example has this feature (see screenshots attached), but their tile can only control SamsungTVs and can not be customized (like change source, launch an app etc.)

![Screenshot_20240917_234949_sysui](https://github.com/user-attachments/assets/9cb7d823-4bfe-490f-b73c-dec58a5cd7ce)

![Screenshot_20240917_234954_oneconnect](https://github.com/user-attachments/assets/78360dd3-1e85-48ec-b7a8-7d9f8550d2f2)

**Comment by Nerwyn** [comment]
This is a repo for a Home Assistant dashboard custom remote card, not WearOS. It's completely out of scope of this project and would be a request for the Home Assistant developers.
