### ISSUE TITLE
Roku apps button

### ISSUE THREAD

**Issue by mateusfn98** [Nerwyn/android-tv-card#144]
**Is your feature request related to a problem? Please describe.**
I can't add a Netflix button.

**Describe alternatives you've considered**
https://github.com/PRProd/HA-Firemote
I'm using this project in my dashboard and the apps button is working, but I'm only using it for opening apps.

**Additional context**
Hope with this Firemote project documentation, you can integrate 100% your project.

**Comment by Nerwyn** [comment]
[File with app launching information for reference](https://github.com/PRProd/HA-Firemote/blob/main/dist/launcher-buttons.js)

**Comment by Nerwyn** [comment]
It's 10000 lines long 😱

**Comment by Nerwyn** [comment]
Alright I've added a bunch of sources from that list that I already had icons for (or had icons in the MDI icon set) for Android TV, Apple TV, Fire TV, and Roku. Give it a try in the 4.1.0 alpha!

**Comment by Nerwyn** [comment]
[Released 4.1.0.](https://github.com/Nerwyn/android-tv-card/releases/tag/4.1.0)
