### ISSUE TITLE
Not showing the visual editor buttons tab.

### ISSUE THREAD

**Issue by mateusfn98** [Nerwyn/android-tv-card#146]
**Release with the issue:**
4.1.0
**Last working release (if known):**
4.0.6
**Browser and Operating System:**
Brave - Windows / Ubuntu Server - Homeassistant Container

**Description of problem:**
It is not showing the add buttons configuration in the visual editor.
![image](https://github.com/user-attachments/assets/19eb262e-8871-49c7-86de-9cec9e7e1144)

**Additional information:**
But I've added the netflix/jellyfin/youtube/primevideo manually in yaml and it's working great :DD

**Comment by Nerwyn** [comment]
Which version of Home Assistant core on you on? And which type of dashboard?

**Comment by mateusfn98** [comment]
I didn't know what happened, but now is working :D 
Thanks!
![image](https://github.com/user-attachments/assets/078963eb-28f2-449a-8872-380f4594e854)
