### ISSUE TITLE
Add "WaipuTV" as Option

### ISSUE THREAD

**Issue by MickLesk** [Nerwyn/android-tv-card#147]
**Is your feature request related to a problem? Please describe.**
Nope, not an problem, just a request

**Describe the solution you'd like**
Add an new Icon for WaipuTV (German Streaming like hulu in USA)

SVG for Example from Custom-Brand-Icons Repo:
https://github.com/elax46/custom-brand-icons/blob/main/icon-svg/waiputv.svg

**Describe alternatives you've considered**
Add a new source for WaipuTV.

If you need help with the source call, I just need to know how to find out. Waipu runs on my Google TV as well as on my LG WebOS and Samsung SmartTV

WebOS: https://de.lgappstv.com/main/tvapp/detail?appId=1087412&catCode1=&moreYn=N&cateYn=N&orderType=0&headerName=&appRankCode=&sellrUsrNo=

Google: https://play.google.com/store/apps/details?id=de.exaring.waipu&hl=de

**Comment by Nerwyn** [comment]
I always need the sources for the apps. The Home Assistant integration documentation may help ([Android TV](https://www.home-assistant.io/integrations/androidtv_remote/#launching-apps) and [LG webOS](https://www.home-assistant.io/integrations/webostv/#sources)).

**Comment by Nerwyn** [comment]
I've found default sources for WaipuTV and Wow for Android TV, Fire TV, and Apple TV using the [HA-Firemote](https://github.com/PRProd/HA-Firemote/blob/main/dist/launcher-buttons.js) defaults list, but it doesn't include LG or Samsung TV.

**Comment by MickLesk** [comment]
Ah i checked your Code,
Do you only emulate buttons and can't call up apps directly? There is no physical button for these two apps (WaipuTV and WOW), on LG you can only map them to a button 1-9. On Samsung it is probably only possible via the Apptray.

Or can you also call up sources directly without them being on the remote control?

**Comment by Nerwyn** [comment]
It has nothing to do with the physical remote buttons. We're limited to home Assistant service calls (or perform actions as they've now been renamed) You'll have to use the [LG Home Assistant integration](https://www.home-assistant.io/integrations/webostv/#sources) and the [Samsung TV custom integration](https://github.com/ollo69/ha-samsungtv-smart) documentation to figure out how to open these apps using them.

**Comment by MickLesk** [comment]
LG (cropped) 
source_list:
  - Amazon Alexa
  - Disney+
  - Netflix
  - Prime Video
  - Rakuten TV
  - WOW
  - YouTube
  - waipu.tv
volume_level: 0.09
is_volume_muted: false
source: waipu.tv

**Comment by Nerwyn** [comment]
To clarify, these are all sources you've confirmed are working with the Home Assistant action:

```yaml
action: media_player.play_media
target:
  entity_id: media_player.lg_webos_smart_tv
data:
  media_content_id: "Netflix"
  media_content_type: "channel"
```

**Comment by MickLesk** [comment]
> To clarify, these are all LG webOS TV sources you've confirmed are working with this Home Assistant action?

yep, ive used the developer tools, where I can display the values. Samsung is slow to respond, but I hope to get it connected correctly today :-)

![image](https://github.com/user-attachments/assets/5e51825b-a099-41ac-a93b-b5ec36c70cfb)

**Comment by Nerwyn** [comment]
Wait I think I misread the LG webOS documentation. Is it the action `media_player.select_source`, or `media_player.play_media`? I thought it was the latter but reading the documentation again and seeing your screenshot it looks like it's the former.

**Comment by Nerwyn** [comment]
I've added your sources in the latest 4.1.1 alpha. I also decided to expand the `key` and `source` actions to work with all platforms https://github.com/Nerwyn/android-tv-card/blob/dev/src/classes/base-remote-element.ts#L169-L227.

**Comment by Nerwyn** [comment]
@MickLesk I'm going to work on release the next patch version without the Samsung sources.

**Comment by Nerwyn** [comment]
Added WaipuTV source to various platforms in [4.1.1](https://github.com/Nerwyn/android-tv-card/releases/tag/4.1.1).
