### ISSUE TITLE
Add "WOW" as Option

### ISSUE THREAD

**Issue by MickLesk** [Nerwyn/android-tv-card#148]
**Is your feature request related to a problem? Please describe.**
Nope, not an problem, just a request

**Describe the solution you'd like**
Add an new Icon for WOW (former SKY in Germany)

SVG for Example from Custom-Brand-Icons Repo:
https://github.com/elax46/custom-brand-icons/blob/main/icon-svg/sky-alt.svg

**Describe alternatives you've considered**
Add a new source for WOW.

If you need help with the source call, I just need to know how to find out. Waipu runs on my Google TV as well as on my LG WebOS and Samsung SmartTV

WebOS: https://de.lgappstv.com/main/tvapp/detail?appId=274543&catCode1=&moreYn=N&cateYn=N&orderType=0&headerName=%EC%A0%84%EC%B2%B4&appRankCode=&sellrUsrNo=&curPage=1

Google: https://play.google.com/store/apps/details?id=de.sky.online&hl=de

**Comment by Nerwyn** [comment]
That icon seems out of date. Would this one be more appropriate?
https://seeklogo.com/vector-logo/439511/wow-sky

**Comment by MickLesk** [comment]
Yep, there are x types of Sky here in Germany. But I think it's all WOW by now

**Comment by Nerwyn** [comment]
Added wow default source to various platforms in [4.1.1](https://github.com/Nerwyn/android-tv-card/releases/tag/4.1.1).
