### ISSUE TITLE
Picture Preset for TCL's Android TV

### ISSUE THREAD

**Issue by romquenin** [Nerwyn/android-tv-card#152]
**Is your feature request related to a problem? Please describe.**
Is it possible to change the Picture preset of a TCL's Android TV (Dynamic, Cinema, Standard, etc...)

**Describe the solution you'd like**
Would love to have a button for each preset to be able to change the preset depending on the source.

**Describe alternatives you've considered**
I have a Samsung Smart TV and i can change the picture mode with this TV.

**Comment by romquenin** [comment]
Unfortunately after some research i don't think this can be changed via the Android TV API.

**Comment by Nerwyn** [comment]
Unfortunately there's nothing we can do to implement it as as default key.

If you have a smart IR remote like a Broadlink, you can use it to send the command locally via Home Assistant and create a custom action to do so.

**Comment by romquenin** [comment]
Thanks @Nerwyn i will try to do that with my Harmony Remote
