### ISSUE TITLE
send mqtt command ?

### ISSUE THREAD

**Issue by myB0B** [Nerwyn/android-tv-card#164]
is it possible to send mqtt command on press button ?
i'm looking for a remote card with touchpad capability who send custom mqtt command

**Comment by Nerwyn** [comment]
You should be able to with this or any other card that supports Home Assistant actions/services using the `mqtt.publish` action. You can remap the touchpad to send `mqtt.publish` actions as well.

**Comment by myB0B** [comment]
Ok, thank you, but I found another solution.
