### ISSUE TITLE
any chance you can add jellyfin support?

### ISSUE THREAD

**Issue by zombiehoffa** [Nerwyn/android-tv-card#165]
it would be super awesome if this remote just worked with this: https://www.home-assistant.io/integrations/jellyfin/

so I could easily create remotes for my jellyfin boxes.

**Comment by Nerwyn** [comment]
Available in the 4.3.0 alpha. Most of the commands listed in [this file](https://github.com/jellyfin/jellyfin/blob/master/MediaBrowser.Model/Session/GeneralCommandType.cs) don't seem to do anything though. I added all of the ones that don't require additional information that cannot be provided through the Home Assistant `remote.send_command` action.

**Comment by Nerwyn** [comment]
@zombiehoffa Jellyfin support is now in 4.3.0 beta, if you have any feedback.

**Comment by Nerwyn** [comment]
Added Jellyfin as a default platform in [4.3.0](https://github.com/Nerwyn/android-tv-card/releases/tag/4.3.0)
