### ISSUE TITLE
buttons based on condition

### ISSUE THREAD

**Issue by Gtasian** [Nerwyn/android-tv-card#17]
**Is your feature request related to a problem? Please describe.**
1. The touchpad can be hard to use on platforms like PC so I would like the ability to toggle (to buttons) or hide. 
2. I like the ability to add buttons but it can get cluttered really quickly.

**Describe the solution you'd like**
Have conditions and/or toggleable buttons in the card to choose a "layout" This could help in hiding all app icons while viewing content. 

**Describe alternatives you've considered**
Making a vertical stack card filled with conditional cards that feature different android-tv-cards

**Additional context**

**Comment by Nerwyn** [comment]
Conditional buttons are a bit out of scope of this project, but can be done using [card-mod](https://github.com/thomasloven/lovelace-card-mod). I was able to get touchpad and dpad to alternate based on orientation (not sure how to do it for device type) like so:
```yaml
rows:
  - - navigation_buttons
  - - navigation_touchpad
card_mod:
  style: |
   .row:has(ha-icon-button[title="center"]) {
      @media (orientation: portrait) {
        display: none;
      }
    }
    .row:has(toucharea) {
      @media (orientation: landscape) {
        display: none;
      }
    }
```
Personally I use [layout-card](https://github.com/thomasloven/lovelace-layout-card) to create different layouts for landscape and portrait in horizontal/vertical stacks like you mentioned above.

**Comment by Nerwyn** [comment]
In addition to the above method, you can now also conditionally set elements using templating as of [v3.1.0](https://github.com/Nerwyn/android-tv-card/releases/tag/v3.1.0).

```yaml
rows: 
 - - '{{ "navigation_buttons" if match_media("(orientation: landscape)") else "navigation_touchpad" }}'
```

Using templates, you could probably also create a button which controls an `input_select` entity, and then use an `is_state()` template check to determine which element to display.

**Comment by Nerwyn** [comment]
Here's an example of how to use the new templates to toggle different buttons.

```
type: custom:android-tv-card
rows:
  - - next_thing
    - |
      {% if is_state("input_select.test_select", "A") %}
      n1
      {% elif is_state("input_select.test_select", "B") %}
      n2
      {% else %}
      n3
      {% endif %}
custom_keys:
  next_thing:
    icon: mdi:skip-next-circle
    service: input_select.select_next
    data:
      cycle: true
    target:
      entity_id: input_select.test_select

```
