### ISSUE TITLE
use custom keys to open url or other HA actions.

### ISSUE THREAD

**Issue by Montreal666** [Nerwyn/android-tv-card#33]
**Is your feature request related to a problem? Please describe.**
Enhancement 

**Describe the solution you'd like**
 use custom keys to open a web page/url other HA actions, beyond Call-service.

Ex:
tap_action:
  action: url
  url_path: https:www.google.com

Would translate to something like this :

custom_keys:
  center:
    action: url
    url_path: https:www.google.com

Thanks!

**Describe alternatives you've considered**
I’ve tried services like shell_command / rest_command unsuccessfully

**Comment by Nerwyn** [comment]
Combining work on this with https://github.com/Nerwyn/android-tv-card/issues/31 and taking notes there.
