### ISSUE TITLE
Primevideo opening not opening Indian prime video app

### ISSUE THREAD

**Issue by vineeshvijayan2020** [Nerwyn/android-tv-card#43]
**Is your feature request related to a problem? Please describe.**
When primevideo is added it opens primevideo link to download US prime video. I need it top open primevideo in Indian playstore

**Describe the solution you'd like**
 I need it top open primevideo in Indian playstore

**Describe alternatives you've considered**

**Additional context**

**Comment by Nerwyn** [comment]
From the sounds of it the prime video app for India may be a different app altogether. You'll have to find the deep link for it using [this guide](https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921) and create a custom source for it.
