### ISSUE TITLE
Put patch notes at the top of release descriptions

### ISSUE THREAD

**Issue by DarkFox** [Nerwyn/android-tv-card#54]
**Is your feature request related to a problem? Please describe.**
It's unintuitive that patch notes are at the bottom of the release descriptions, as Home Assistant requires expanding it and scrolling down to see them (I genuinely believed that you were just re-using the same description for subsequent patch releases).

**Describe the solution you'd like**
Prepend the patch notes at the top of the release notes, possibly with a headline of "Changes in vX.X.1", that way the user can follow the trail of patches back to the major release, in case they skipped one or more versions.

**Comment by Nerwyn** [comment]
I have been copying the release notes for patch releases and adding to the patch changes at the bottom. I'll start also copying the release specific patch changes to the top of the release for patch changes, and modify the last few releases to match.
