### ISSUE TITLE
Add option for how many times hold action is repeated per second

### ISSUE THREAD

**Issue by Simsala91** [Nerwyn/android-tv-card#60]
Currently, when you hold a button or the touchpad, it will repeat the action 10x per second. Personally, I think this is too much. But this mostly comes down to personal preference.

**Describe the solution you'd like**
Add an option that changes how often a button is repeated per second.
This could be an optional config for the card, for example:

```
type: custom:android-tv-card
remote_id: remote.google_chromecast
slider_id: media_player.google_chromecast
keyboard_id: media_player.google_chromecast_adb
hold_actions_per_second: 5   #default 10
...

```

**Comment by Nerwyn** [comment]
Good idea, but it would make more sense to let users redefine the delay rather than the frequency. So something like `repeat_delay` with a default value of 100 (ms). I should also try to make this configurable for either all repeats or at a custom action level.

**Comment by Nerwyn** [comment]
Implemented in 3.4.0, which is still in alpha as I implemented other feature requests.

**Comment by Nerwyn** [comment]
Ready to for testing and feedback in [3.4.0-beta.001](https://github.com/Nerwyn/android-tv-card/releases/tag/3.4.0-beta.001)!

**Comment by Simsala91** [comment]
Tested both global setting and global setting + individual setting for action and looks very good , everything responding as expected 👍 Thank you! :)
