### ISSUE TITLE
[FR] Define Custom Volume Entity

### ISSUE THREAD

**Issue by zimmra** [Nerwyn/android-tv-card#7]
I would like to be able to associate the volume slider with a separate entity (in my case, an AV receiver) 

Currently I can assign custom volume buttons to it, but not the slider. 

I would think a new config option e.g. volume_entity and if present it overrides the media player as default volume control endpoint would do the trick.

**Comment by Nerwyn** [comment]
You should be able to already do this using the `media_player_id` input. After forking this project all commands previously made using `media_player.play_media` and `media_player.change_source` were changed to `remote.send_command` and `remote.turn_on`, leaving the volume slider as the only entity that still used the media player entity. Try setting `media_player_id` to your AV receiver media player entity ID. I just tried it and it worked fine.
