### ISSUE TITLE
Can you add internal access URL Action Types?

### ISSUE THREAD

**Issue by Ainndy** [Nerwyn/android-tv-card#71]
For example, use RESTful Command to access http.

**Comment by Nerwyn** [comment]
I'm not sure what you mean. As it is now this card supports both [navigate](https://github.com/Nerwyn/android-tv-card?tab=readme-ov-file#navigate) and [url](https://github.com/Nerwyn/android-tv-card?tab=readme-ov-file#url) actions.

**Comment by Ainndy** [comment]
> I'm not sure what you mean. As it is now this card supports both [navigate](https://github.com/Nerwyn/android-tv-card?tab=readme-ov-file#navigate) and [url](https://github.com/Nerwyn/android-tv-card?tab=readme-ov-file#url) actions.

I used call-service, Thank you.
