### ISSUE TITLE
Max button does not start Max app on Google TV

### ISSUE THREAD

**Issue by Mike-Burger** [Nerwyn/android-tv-card#77]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
3.5.2

**Last working release (if known):**
Unknown

**Browser and Operating System:**
Chrome, Windows

**Description of problem:**
When using the default rows, "max" populates the Max logo, but does not cause the Google TV to show the cast app. On the TV, there is an error that says 'You don't have an app that can do this'; however, I do have the Max app installed.

This might be due to the switch from HBO Max app to Max app.

All other default rows I have tried work as expected.

**Comment by Nerwyn** [comment]
[Max is known to be broken](https://github.com/Nerwyn/android-tv-card/blob/main/src/models/maps/defaultSources.ts#L37), despite the default Max source having the deep link listed in [the Android TV Deep Linking Guide thread](https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921/229). I'm not sure if this is an inconsistency between Android TVs or if the deep link in the guide is incorrect.

**Comment by Mike-Burger** [comment]
Unlucky - hopefully someone better than me can find it. I tried and tested potential deeplinks, but none worked.

**Comment by felipecrs** [comment]
```console
market://launch?id=com.wbd.stream
```

This is the best I found so far.

**Comment by felipecrs** [comment]
This will make things easier btw: https://github.com/home-assistant/core/pull/116906

**Comment by Nerwyn** [comment]
@felipecrs https://github.com/home-assistant/core/pull/116906 has been merged, but the deep link you shared opens the app page for Max, not Max itself. Any idea how to open Max itself?

**Comment by felipecrs** [comment]
No idea, but that's better than nothing.

**Comment by Nerwyn** [comment]
I guess I can push out another patch version that changes the Max source to this, but I'm going to leave this open until we get a true Max link.

**Comment by krissen** [comment]
There must be some app-side difference because some apps, when called by their bundle-ID, open the actual app; others, like Max, open the app-page. 

My workaround is to add a 300ms delay for the latter category of apps, and then an additional push of the center-button. Hacky, but works.

But we might need to wait for an update of the app itself.

**Comment by skavan** [comment]
FWIW, this is working for me - on a chromecast and a Google TV inside a Hisense.
I had to delete and reinstall Max on the devices.
- name: max
  type: button
  tap_action:
    action: source
    source: https://play.max.com

**Comment by Nerwyn** [comment]
@skavan you're right! Looks like the app creates finally fixed the deep link. I'll change it to that for the Android TV default source.

I wasn't able to get the Fire TV command working on Android TV via ADB, but I can try changing it in a patch version alpha for you to test.

**Comment by Nerwyn** [comment]
Fixed in [4.2.1](https://github.com/Nerwyn/android-tv-card/releases/tag/4.2.1)
