### ISSUE TITLE
Volume slider does not work with Android TV Remote integration?

### ISSUE THREAD

**Issue by jockebq** [Nerwyn/android-tv-card#80]
I have a weird issue. My Chromecast with Google TV is configured as a Google Cast device. Volume control here is no problem. Downloaded this component and used the Android TV Remote integration to add my Chromecast with Google TV once again to be able to be controlled with this touch pad remote.

It all works except if I use the Volume slider. If I use the volume buttons I have no issues. But if I use the slider and the Android TV Remote it will not control the volume.
![image](https://github.com/Nerwyn/android-tv-card/assets/40036309/49ebac9c-2fe1-474d-870a-c8760ead7e50)

I get this error.
But if I change it to my Google Cast media player I can control the volume with the slider. However it is buggy and will not report current volume.

How come the slider doesn’t work but the buttons do with Android TV Remote?
The volume is controlled by the CCwGTV, not via CEC or anything.

Thank you!

**Comment by Nerwyn** [comment]
1. You ignored the bug report template and are missing important information like your remote config and console errors.
2. It says right on the bottom of your screenshot that your chromecast does not support the service `media_player.set_volume`.

The volume buttons use the service `remote.send_command` with the key `VOLUME_UP/DOWN`, the volume slider uses the service `media_player.volume_set`. If a media player (in this case Chromecast with Google TV) doesn't support the latter service, then you cannot use the slider with it.

**Comment by jockebq** [comment]
> 1. You ignored the bug report template and are missing important information like your remote config and console errors.
> 
>     2. It says right on the bottom of your screenshot that your chromecast does not support the service `media_player.set_volume`.
> 
> 
> The volume buttons use the service `remote.send_command` with the key `VOLUME_UP/DOWN`, the volume slider uses the service `media_player.volume_set`. If a media player (in this case Chromecast with Google TV) doesn't support the latter service, then you cannot use the slider with it.

Sorry about that, it went a little too quick. But I don't understand why the device would support this feature when using the same device through the media_player Google Cast, I have no issues changing volume with the slider. But it will not report back the state. But no with the Android TV Remote, which does in fact report the state correctly, but will not allow the change. I know the device does support it, but not the integration?

**Comment by Nerwyn** [comment]
That's a question for the developer of the Home Assistant Android TV integrations, not me or here. The Android TV ADB integration also supports the service `media_player.set_volume` and can be used instead.
