### ISSUE TITLE
Keyboard mode for Roku

### ISSUE THREAD

**Issue by dgoodwin430** [Nerwyn/android-tv-card#81]
**Is your feature request related to a problem? Please describe.**

Keyboard does not support Roku players.

**Describe the solution you'd like**

Adapted code for Roku players

**Describe alternatives you've considered**

None

**Additional context**

Reference code for roku keyboard integration.
https://github.com/PRProd/HA-Firemote

**Comment by Nerwyn** [comment]
You wouldn't happen to know where the actual code for sending keyboard keys to Roku is would you?

**Comment by Nerwyn** [comment]
I did find this bit on the Home Assistant Roku page: https://www.home-assistant.io/integrations/roku/#services

**Comment by Nerwyn** [comment]
Found it! https://github.com/PRProd/HA-Firemote/blob/v3.4.0/dist/HA-Firemote.js#L4764. I'm not sure why this isn't in the Home Assistant Roku integration page.

This does present a problem. Sending text one letter at a time uses the Roku remote entity, while sending it via global search uses the media player entity ID. This card does have separate fields for remote and media player entity ID, so I can include some weird logic for check the keyboard ID domain and also sending commands to the remote or media player ID instead.

**Comment by dgoodwin430** [comment]
Sorry, I wasn't able to get back to you yesterday. Yes, that's the line I was looking at but I wasn't sure it was enough to build off of. I thought it might end up being some weird logic since it only takes one letter at a time instead of a bulk send. I wasn't really sure how to approach it.

**Comment by Nerwyn** [comment]
@dgoodwin430 I just released [3.7.0-beta.001](https://github.com/Nerwyn/android-tv-card/releases/tag/3.7.0-beta.001), which adds Roku keyboard support for the seamless `keyboard`, bulk `textbox`, and global `search` modes. Can you thoroughly test it and give me feedback? I don't have a Roku so I have no idea if it works.

**Comment by dgoodwin430** [comment]
@Nerwyn  from basic testing the keyboard functionality seems to be working great! I will let you know if I come across anything. Great work!

**Comment by Nerwyn** [comment]
Great! If you don't run into any other issues over the next few days I'll release this later this week.

**Comment by Nerwyn** [comment]
Released [3.7.0](https://github.com/Nerwyn/android-tv-card/releases/tag/3.7.0).
