### ISSUE TITLE
Star+ icon

### ISSUE THREAD

**Issue by felipecrs** [Nerwyn/android-tv-card#85]
It would be great if you could bundle a Star+ icon + button.

https://icon-sets.iconify.design/cbi/star-plus/

**Comment by Nerwyn** [comment]
TODO: Merge PRs for this and Samsung example, and then update `ha-nunjucks` to solve numerical string truncation issue once the latter fix is confirmed working for service-call-tile-feature.

**Comment by felipecrs** [comment]
Don't worry, no rush at all.

**Comment by Nerwyn** [comment]
Released [3.7.1](https://github.com/Nerwyn/android-tv-card/releases/tag/3.7.1).
