### ISSUE TITLE
Smart mute/unmute icon

### ISSUE THREAD

**Issue by felipecrs** [Nerwyn/android-tv-card#86]
It would be nice if the card could automatically detect whether the volume is 0% or not and render the mute icon for the mute button as muted/unmuted.

**Comment by Nerwyn** [comment]
This would be out of scope of the project, as determining what indicates whether the volume is 0% is not standard if the user doesn't link a media player to this card. You can however do it yourself using templates.

```
custom_actions:
  volume_mute:
    icon: |-
      {% if is_state_attr("media_player.lounge_chromecast", "is_volume_muted", true) or is_state_attr("media_player.lounge_chromecast", "volume_level", 0) %}
      mdi:volume-variant-off
      {% else %}
      mdi:volume-low
      {% endif %}
```

**Comment by felipecrs** [comment]
That's awesome. Thanks a lot for the template.
