### ISSUE TITLE
dpad not in the middle

### ISSUE THREAD

**Issue by vednolacni** [Nerwyn/android-tv-card#88]
![Screenshot_2024-05-24-13-13-06-085_io.homeassistant.companion.android.jpg](https://github.com/Nerwyn/android-tv-card/assets/123391433/f0b98341-d060-4b94-be39-99496445527a)

As the title say. Is there a way fix this?

Edit: Im using the buuble card - pop up.

**Comment by Nerwyn** [comment]
A chromium webview update from a few months ago broke my Google dpad style example but I've neglected to fix it. I'll need to rework it.

**Comment by Nerwyn** [comment]
It may have not been a webview change but a row style change. Setting `justify-content` to `center` for the row class (or just this row in particular by ID) using card-mod fixes it.

While it is now fixable using card-mod, I should get around to adding a built in way to modify individual row and column styles. I did add unique IDs for each row and column in a car a few release ago, and should add a row/column style field.

**Comment by Nerwyn** [comment]
Your wife's iPhone has a larger horizontal resolution, so it can fit the middle row without squishing the end and causing it to be lopsided.

**Comment by Nerwyn** [comment]
This would also be a good place for me to remember to do the following:
- Use grid for `dpad` instead of rows and columns to help it keep shape at different screen resolutions.
- Add `xpad` and `npad` button layout special elements, also using grid.

**Comment by Nerwyn** [comment]
Turns out grid made the dpad way worse (3.8.0 beta 2). But it's still possible to create and style the old dpad by listing out the buttons. I'll continue working on internal rows styling for 3.8.0 beta 3.

**Comment by Nerwyn** [comment]
@vednolacni you should be able to set row and column styles without card-mod now using `row_styles` in the latest 3.8.0 beta.

**Comment by Nerwyn** [comment]
@vednolacni if you have no feedback on the 3.8.0 beta I'll release it in a few days and then close this issue.

**Comment by Nerwyn** [comment]
Change `dpad` to `nav_buttons`. `dpad` now uses the fixed size grid, which doesn't work with these styles. `nav_buttons` returns the buttons using rows.

**Comment by Nerwyn** [comment]
Row/column style options and special grids added in [3.8.0](https://github.com/Nerwyn/android-tv-card/releases/tag/3.8.0).

**Comment by Nerwyn** [comment]
@vednolacni what does your row style settings look like? Looking at your config the nav buttons are on rows 2, 3, and 4 so it should look like this:

```yaml
row_styles:
  row-2:
    justify-content: center
  row-3:
    justify-content: center
  row-4:
    justify-content: center
```
