### ISSUE TITLE
Please Help for Volume Slider Bug 

### ISSUE THREAD

**Issue by muktheo** [Nerwyn/android-tv-card#92]
Hi, it seems my volume slider has a little bug. Everytime I change the slide value, it will come back to the center. The volume has changed normally but not the slider.

bytheway Ive been using your incredible works for long time, and I notice that im still using old config like media_player instead of slider_id, adb_id, etc.
but even after change it to slider_id or the newest, the bug still there.

thank you

```type: custom:android-tv-card
remote_id: remote.tv_ruang_tamu #android tv remote
keyboard_id: media_player.android_tv_192_168_2_92 #adb
slider_id: media_player.tv_ruang_tamu_gcast #google cast
rows:
  - - power
    - keyboard
    - search
  - - back
    - home
    - tv
  - - youtube
    - spotify
    - netflix
  - - navigation_touchpad
  - - slider
  - - channel_up
    - channel_down
    - info
  - - rewind
    - play
    - pause
    - fast_forward
button_style:
  '--size': 62px
  color: '#00ccff'
touchpad_style:
  height: 250px
```
![image](https://github.com/Nerwyn/android-tv-card/assets/145354403/f2cdad4d-a32f-4d00-a4de-ab2588aeb085)

**Comment by Nerwyn** [comment]
Which version are you on? I accidentally introduced a bug that causes this in 3.7.1 but fixed it in 3.7.2. Also use three backticks ``` for code blocks and one backtick for inline code.

**Comment by muktheo** [comment]
I'm on 3.7.4 version right now. And thank you for reminding about block ticks

**Comment by Nerwyn** [comment]
Can you try clearing browser cache? It really does sound like the 3.7.1 bug which is fixed.

What about adding this to your config to debug?
```yaml
  slider:
    style:
      '--color': hsl(211, {{ value * 100 }}%, {{ value * 100 }}%)
      '--value': '{{ value }}'
```

Does the color change as you move the slider? Does it also revert color? Can you open the browser developer tools, select the slider, and see the value of `--value` change and revert?

**Comment by mikekornikh** [comment]
I have the same issue! Started after one of the more recent updates

**Comment by mikekornikh** [comment]
Oh, and I double checked the media player entity and it's showing the correct volume level percentage

**Comment by Nerwyn** [comment]
The config above isn't supposed to help, just give more visibility into what's going on. Did y'all clear cache? This should already be fixed, but I'll look into and modify the slider config setting code in the 3.8.0 beta to see if I can identify anything else that could be causing it.

**Comment by mikekornikh** [comment]
> The config above isn't supposed to help, just give more visibility into and help diagnose what's going on. Did y'all clear cache? This should already be fixed, but I'll look into and modify the slider config setting code in the 3.8.0 beta to see if I can identify anything else that could be causing it.

yup, cleared cache, still rebounds back to 50%,. The same thing happens in Android and iPhone apps too.

**Comment by Nerwyn** [comment]
What version are you on? Can you try the latest release version or 3.8.0 beta? What's your remote config?

**Comment by Nerwyn** [comment]
Can y'all try the latest beta again? I think I've identified and fixed the issue, and @muktheo's config is now working for me.

**Comment by muktheo** [comment]
> Can y'all try the latest beta again? I think I've identified and fixed the issue, and @muktheo's config is now working for me.

great, confirm the slider working normally on latest beta.

thanks so much for you hardwork

**Comment by Nerwyn** [comment]
Sorry it took me a bit to get to fixing it. As new features get added and fields get changed and deprecated the chances I break deprecated config support increases and more difficult to diagnose.

**Comment by mikekornikh** [comment]
The beta worked for me too! Thank you so much!

**Comment by Nerwyn** [comment]
Fixed sliders when only slider ID is provided in [3.8.0](https://github.com/Nerwyn/android-tv-card/releases/tag/3.8.0)
