### ISSUE TITLE
Volume doesn't work

### ISSUE THREAD

**Issue by 1mfaasj** [Nerwyn/android-tv-card#99]
Hi I've got an issue with the volume which doesn't work/respond. Any idea what is causing this? the rest of the controls are working fine though,
how my code looks like:

```
type: custom:android-tv-card
remote_id: remote.chromecastzolder
keyboard_id: media_player.chromecast_zolder
rows:
  - - back
    - power
    - home
    - search
  - - volume_down
    - volume_mute
    - volume_up
  - - navigation_buttons
  - - netflix
    - youtube
    - disney
    - spotify
    - nlziet
    - videoland
  - - previous
    - rewind
    - play_pause
    - fast_forward
    - next
```

I enabled and using the following HA integrations:
- Android TV Remote:
     remote.chromecastzolder
     media_player.chromecastzolder
- Android Debug Bridge:
     media_player.androidtvzolder
- Google cast:
     sensor.chromecast_zolder

I've tried all three without success.
What I noticed is that the volume buttons on the entity (at the integration page) is't working either. So what I mean:
![image](https://github.com/Nerwyn/android-tv-card/assets/71582854/4d083444-9d0e-44ba-9460-095d9895727f)

If you know a workaround or maybe a way to control the volume with an adb command (?) please let me know.

**Comment by Nerwyn** [comment]
If it isn't working in the Home Assistant more info popup, then it isn't an issue with this card and shouldn't be labeled as a bug.

How are your speakers setup?

**Comment by 1mfaasj** [comment]
It could be card related right but I tested all media integrations and volume doesn't work anywhere so I need to fix that first
You may close the ticket 
Thanks for replying anyway!
